added

diff --git a/.github/workflows/tanvir.yml b/.github/workflows/tanvir.yml
--- a/.github/workflows/tanvir.yml
+++ b/.github/workflows/tanvir.yml
@@ -29,9 +29,24 @@ jobs:
        - name: print user inputs
          run: |
              echo "user input: ${{github.event.inputs.example_input}}"
+       - name: check the user input 
+         run: |
+            if["${{github.event.inputs.example_input}}"= "staging"];then
+              echo "you chose staging server"
+
+            elif["${{github.event.inputs.example_input}}"= "production"];then
+              echo "you chose production server"
+            else 
+             echo "invalid input"
+             exit 1 
+            fi    
+            
+       
        - name: print contents of txt file
          run : |
           cat tanvir.txt
+
+       
 
 
 
